-- AlterTable
ALTER TABLE "Draft" ADD COLUMN "chemistryEnabled" BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE "Draft" ADD COLUMN "coachEnabled" BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE "Draft" ADD COLUMN "ageEnabled" BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE "Draft" ADD COLUMN "potentialEnabled" BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE "Draft" ADD COLUMN "fitEnabled" BOOLEAN NOT NULL DEFAULT 1;
