
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Do not use env("DATABASE_URL") here — that throws during `prisma generate`
    // (postinstall / Vercel build) when the variable is not set yet.
    url: process.env.DATABASE_URL ?? "file:./dev.db",
  },
});
