
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Do not use env("DATABASE_URL") here — that throws during `prisma generate`
    // (postinstall / Vercel build) when the variable is not set yet.
    // DIRECT_URL (session/direct, port 5432) is required for migrate on
    // Supabase transaction poolers. Fall back to DATABASE_URL otherwise.
    url:
      process.env.DIRECT_URL ??
      process.env.DATABASE_URL ??
      "postgresql://postgres:postgres@localhost:5432/soccer_game",
  },
});
