-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Player" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "positions" TEXT NOT NULL,
    "nationality" TEXT NOT NULL,
    "club" TEXT NOT NULL DEFAULT '',
    "league" TEXT NOT NULL DEFAULT '',
    "overall" INTEGER NOT NULL,
    "potential" INTEGER NOT NULL,
    "age" INTEGER NOT NULL,
    "dob" TEXT NOT NULL,
    "heightCm" INTEGER NOT NULL,
    "weightKg" INTEGER NOT NULL,
    "valueEur" INTEGER NOT NULL,
    "wageEur" INTEGER NOT NULL,
    "preferredFoot" TEXT NOT NULL,
    "weakFoot" INTEGER NOT NULL,
    "skillMoves" INTEGER NOT NULL,
    "internationalReputation" INTEGER NOT NULL,
    "workRate" TEXT NOT NULL,
    "pace" INTEGER NOT NULL,
    "shooting" INTEGER NOT NULL,
    "passing" INTEGER NOT NULL,
    "dribbling" INTEGER NOT NULL,
    "defending" INTEGER NOT NULL,
    "physic" INTEGER NOT NULL,
    "imageUrl" TEXT NOT NULL,
    "attackingCrossing" INTEGER NOT NULL,
    "attackingFinishing" INTEGER NOT NULL,
    "attackingHeadingAccuracy" INTEGER NOT NULL,
    "attackingShortPassing" INTEGER NOT NULL,
    "attackingVolleys" INTEGER NOT NULL,
    "skillDribbling" INTEGER NOT NULL,
    "skillCurve" INTEGER NOT NULL,
    "skillFkAccuracy" INTEGER NOT NULL,
    "skillLongPassing" INTEGER NOT NULL,
    "skillBallControl" INTEGER NOT NULL,
    "movementAcceleration" INTEGER NOT NULL,
    "movementSprintSpeed" INTEGER NOT NULL,
    "movementAgility" INTEGER NOT NULL,
    "movementReactions" INTEGER NOT NULL,
    "movementBalance" INTEGER NOT NULL,
    "powerShotPower" INTEGER NOT NULL,
    "powerJumping" INTEGER NOT NULL,
    "powerStamina" INTEGER NOT NULL,
    "powerStrength" INTEGER NOT NULL,
    "powerLongShots" INTEGER NOT NULL,
    "mentalityAggression" INTEGER NOT NULL,
    "mentalityInterceptions" INTEGER NOT NULL,
    "mentalityPositioning" INTEGER NOT NULL,
    "mentalityVision" INTEGER NOT NULL,
    "mentalityPenalties" INTEGER NOT NULL,
    "mentalityComposure" INTEGER NOT NULL,
    "defendingMarkingAwareness" INTEGER NOT NULL,
    "defendingStandingTackle" INTEGER NOT NULL,
    "defendingSlidingTackle" INTEGER NOT NULL,
    "goalkeepingDiving" INTEGER NOT NULL,
    "goalkeepingHandling" INTEGER NOT NULL,
    "goalkeepingKicking" INTEGER NOT NULL,
    "goalkeepingPositioning" INTEGER NOT NULL,
    "goalkeepingReflexes" INTEGER NOT NULL
);
INSERT INTO "new_Player" ("age", "attackingCrossing", "attackingFinishing", "attackingHeadingAccuracy", "attackingShortPassing", "attackingVolleys", "defending", "defendingMarkingAwareness", "defendingSlidingTackle", "defendingStandingTackle", "dob", "dribbling", "fullName", "goalkeepingDiving", "goalkeepingHandling", "goalkeepingKicking", "goalkeepingPositioning", "goalkeepingReflexes", "heightCm", "id", "imageUrl", "internationalReputation", "mentalityAggression", "mentalityComposure", "mentalityInterceptions", "mentalityPenalties", "mentalityPositioning", "mentalityVision", "movementAcceleration", "movementAgility", "movementBalance", "movementReactions", "movementSprintSpeed", "name", "nationality", "overall", "pace", "passing", "physic", "positions", "potential", "powerJumping", "powerLongShots", "powerShotPower", "powerStamina", "powerStrength", "preferredFoot", "shooting", "skillBallControl", "skillCurve", "skillDribbling", "skillFkAccuracy", "skillLongPassing", "skillMoves", "valueEur", "wageEur", "weakFoot", "weightKg", "workRate") SELECT "age", "attackingCrossing", "attackingFinishing", "attackingHeadingAccuracy", "attackingShortPassing", "attackingVolleys", "defending", "defendingMarkingAwareness", "defendingSlidingTackle", "defendingStandingTackle", "dob", "dribbling", "fullName", "goalkeepingDiving", "goalkeepingHandling", "goalkeepingKicking", "goalkeepingPositioning", "goalkeepingReflexes", "heightCm", "id", "imageUrl", "internationalReputation", "mentalityAggression", "mentalityComposure", "mentalityInterceptions", "mentalityPenalties", "mentalityPositioning", "mentalityVision", "movementAcceleration", "movementAgility", "movementBalance", "movementReactions", "movementSprintSpeed", "name", "nationality", "overall", "pace", "passing", "physic", "positions", "potential", "powerJumping", "powerLongShots", "powerShotPower", "powerStamina", "powerStrength", "preferredFoot", "shooting", "skillBallControl", "skillCurve", "skillDribbling", "skillFkAccuracy", "skillLongPassing", "skillMoves", "valueEur", "wageEur", "weakFoot", "weightKg", "workRate" FROM "Player";
DROP TABLE "Player";
ALTER TABLE "new_Player" RENAME TO "Player";
CREATE INDEX "Player_overall_idx" ON "Player"("overall");
CREATE INDEX "Player_positions_idx" ON "Player"("positions");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
